# Generated by Django 4.0.4 on 2024-09-30 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BirthCertificateIssue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthcertificatemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
