# Generated by Django 4.0.4 on 2024-10-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BirthCertificateIssue', '0002_birthcertificatemodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthcertificatemodel',
            name='Gender',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
